name: Price Retrieval

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch data
      id: myRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.metals.live/v1/spot'
      
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}

    - name: Update data file
      run: echo '${{ steps.myRequest.outputs.response }}' > data.json

    - name: display data.json content
      run: cat data.json